# Generated by Django 3.1.4 on 2021-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterClients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
            ],
        ),
    ]
